dist: xenial
language: python
python:
  - "3.6"
branches:
  only:
  - source
install:
- pip install -r requirements.txt
script:
#- make publish
- make travis
env:
  global:
    - secure: "XuQ6fvSuHsVKGHpWI0rhB2nQB1GvRZ7hPwP54M72dJ5AVHEH7i6KRr1rwatVcY7fphdX8i8Gm6mVzoG10Ve0wprY8TPbXaTvhwiA3QKI/dz5eZQXEIiS+uqMS9lpKUOIKCEHzjl3e+WT9JNQvh4h9jQ62VbY/3PzpW0nwr+PeixjXPujFQegNgutVoT3/fSLn+Q9FpoEipCuMDxYIbDjreSm5Q/t3t7VFmPBrQuWnJmqLO+dssH4LA7EBe6ptNcsRjCoCma+BJnJvg3ansx7jQtochSQaY8/SABNlzTqCy6hwOKxjCW3v5JoPR4GxpVKmp4tmdhDErkFooRvNBThIuYNJD0p4dkgzNlmFnH5KqgVW1IWpsBHz2PAmAZqK3hdYvZaHe0NI2WB9BW7hHlWFkNTRBmZu4nQudxgEfuA4oNMCy9St+AIW+shgTwMA3BZB25l5SjmiIGv7ZncX45pvXgsK3plIG1BjS8eiOimSRjlD1CE5eVzNEyfG+01rBP2D1xhKlYRQ57iIb+sF1WlWLx08sMgY77SUHO2HlUN1y35LDzTxk4P3sF9mzAlNNPKQ56aP2WF37hTPMYbGvYn3/XgTBGKS1MwyXjFBlr0Pg7Oj5sm58TwJCsK4mkbBB986lw4HPne5Mys+deSlM53tvE+ndj2CR9ou2G3vtQs3YU="

